### ISSUE TITLE
Small batch size will get an unstable result.

### ISSUE THREAD

**Issue by wuwenbin970731** [hsiangyuzhao/Segmentation-Metrics-PyTorch#1]
Thanks for your nice code. But when I use the code to calculate the metrics such as "dice", I encounter a strange problem.When I use a small batch size such as 1,2 or 4, I will get **an unstable result**, but when batch size becomes bigger such as 8 or bigger, the metrics will become stable and lie in a narrow range. And for different model, the small batch size can have a different influence. Some will become smaller than the stable result, and some will become bigger than the stable result.
Have you meet the problem? Looking for your reply, thanks.

**Comment by hsiangyuzhao** [comment]
Thank you for your usage. You see these codes are released some days ago and I am about to make major update to them. Some unnecessary functions will be removed and the new version has been tested to be more stable and correct. Perhaps you can test your data on the new version when it's released. Shall same problems occur, please feel free to present the issue.

**Comment by wuwenbin970731** [comment]
OK！Thanks for your reply.

**Comment by wuwenbin970731** [comment]
Thanks for your nice job! I think I have got the right answers.
